import Vue from 'vue';
import {
  Button,
  NavBar,
  Form,
  Field,
  Toast,
  Tabbar,
  TabbarItem,
  Cell,
  CellGroup,
  Uploader,
  ImagePreview,
  ActionSheet,
  Area,
  Picker,
  Dialog,
  List,
  DropdownMenu,
  DropdownItem,
  IndexBar,
  IndexAnchor,
  Search,
  Popup,
  Overlay,
} from 'vant';

Vue.use(NavBar);
Vue.use(Button);
Vue.use(Form);
Vue.use(Field);
Vue.use(Toast);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Uploader);
Vue.use(ImagePreview);
Vue.use(ActionSheet);
Vue.use(Area);
Vue.use(Picker);
Vue.use(Dialog);
Vue.use(List);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(IndexBar);
Vue.use(IndexAnchor);
Vue.use(Search);
Vue.use(Popup);
Vue.use(Overlay);
